package com.pusilkom.demo.model;

import java.io.Serializable;

public class Institusi implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.institusi.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.institusi.kode_institusi
     *
     * @mbg.generated
     */
    private String kodeInstitusi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.institusi.nama
     *
     * @mbg.generated
     */
    private String nama;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.institusi.nama_singkat
     *
     * @mbg.generated
     */
    private String namaSingkat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.institusi.flag_aktif
     *
     * @mbg.generated
     */
    private Boolean flagAktif;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.institusi
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.institusi.id
     *
     * @return the value of public.institusi.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.institusi.id
     *
     * @param id the value for public.institusi.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.institusi.kode_institusi
     *
     * @return the value of public.institusi.kode_institusi
     *
     * @mbg.generated
     */
    public String getKodeInstitusi() {
        return kodeInstitusi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.institusi.kode_institusi
     *
     * @param kodeInstitusi the value for public.institusi.kode_institusi
     *
     * @mbg.generated
     */
    public void setKodeInstitusi(String kodeInstitusi) {
        this.kodeInstitusi = kodeInstitusi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.institusi.nama
     *
     * @return the value of public.institusi.nama
     *
     * @mbg.generated
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.institusi.nama
     *
     * @param nama the value for public.institusi.nama
     *
     * @mbg.generated
     */
    public void setNama(String nama) {
        this.nama = nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.institusi.nama_singkat
     *
     * @return the value of public.institusi.nama_singkat
     *
     * @mbg.generated
     */
    public String getNamaSingkat() {
        return namaSingkat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.institusi.nama_singkat
     *
     * @param namaSingkat the value for public.institusi.nama_singkat
     *
     * @mbg.generated
     */
    public void setNamaSingkat(String namaSingkat) {
        this.namaSingkat = namaSingkat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.institusi.flag_aktif
     *
     * @return the value of public.institusi.flag_aktif
     *
     * @mbg.generated
     */
    public Boolean getFlagAktif() {
        return flagAktif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.institusi.flag_aktif
     *
     * @param flagAktif the value for public.institusi.flag_aktif
     *
     * @mbg.generated
     */
    public void setFlagAktif(Boolean flagAktif) {
        this.flagAktif = flagAktif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.institusi
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Institusi other = (Institusi) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getKodeInstitusi() == null ? other.getKodeInstitusi() == null : this.getKodeInstitusi().equals(other.getKodeInstitusi()))
            && (this.getNama() == null ? other.getNama() == null : this.getNama().equals(other.getNama()))
            && (this.getNamaSingkat() == null ? other.getNamaSingkat() == null : this.getNamaSingkat().equals(other.getNamaSingkat()))
            && (this.getFlagAktif() == null ? other.getFlagAktif() == null : this.getFlagAktif().equals(other.getFlagAktif()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.institusi
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getKodeInstitusi() == null) ? 0 : getKodeInstitusi().hashCode());
        result = prime * result + ((getNama() == null) ? 0 : getNama().hashCode());
        result = prime * result + ((getNamaSingkat() == null) ? 0 : getNamaSingkat().hashCode());
        result = prime * result + ((getFlagAktif() == null) ? 0 : getFlagAktif().hashCode());
        return result;
    }
}